<?php
declare(strict_types=1);

namespace email;

use jsys\types\email\Address;
use jsys\types\email\Recipient;
use PHPUnit\Framework\TestCase;


class RecipientTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_not_initialize_with_empty_email_address()
    {
        $this->expectExceptionCode(1001);
        $this->expectExceptionMessage("Given string '' is invalid.");
        $recipient = 'something';
        $testEmptyEmail = new Address('');
        $emailAddress = new Recipient($testEmptyEmail,$recipient);
    }

    public function test_can_initialize_with_valid_email()
    {
        $testValidEmail = new Address('hussain@gmail.com');
        $recipient = 'fdfgd';
        $emailAddress = new Recipient($testValidEmail,$recipient);
        $this->assertInstanceOf('jsys\types\email\Recipient', $emailAddress);
        $this->assertEquals('jsys\types\email\Recipient', get_class($emailAddress));
        $this->assertEquals($emailAddress->getEmail(), $emailAddress->getEmail(), 'Both must get the same value');
    }

    public function tearDown(): void
    {
    }
}
