<?php
namespace Jsys\Http\Test;

use PHPUnit\Framework\TestCase;

class MethodTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_it_should_work():void
    {
        $this->assertTrue(true);
    }

    public function it_should_work():void
    {
        $this->assertTrue(true);
    }

    public function it_should_confirm_work():void
    {
        $this->assertTrue(true);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
