<?php
declare(strict_types=1);

namespace email;

use jsys\types\email\Address;
use PHPUnit\Framework\TestCase;


class AddressTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_not_initialize_with_invalid_email()
    {
        $testInvalidEmail = 'hussain@gmail';
        $this->expectExceptionCode(1001);
        $this->expectExceptionMessage("Given string '$testInvalidEmail' is invalid.");
        $emailAddress = new Address($testInvalidEmail);
    }

    public function test_can_initialize_with_valid_email()
    {
        $testValidEmail = 'hussain@gmail.com';
        $emailAddress = new Address($testValidEmail);
        $this->assertInstanceOf('jsys\types\email\Address', $emailAddress);
        $this->assertEquals('jsys\types\email\Address', get_class($emailAddress));
        $this->assertEquals($emailAddress->getEmail(), $testValidEmail, 'Both must get the same value');
    }

    public function tearDown(): void
    {
    }
}
