<?php
declare(strict_types=1);
namespace jsys\types;

use PHPUnit\Framework\TestCase;


class HasSpacesTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_not_initialize_without_any_space()
    {
        $testString = '';
        $this->expectExceptionCode(1023);
        $this->expectExceptionMessage("Given '$testString' has no space");
        $spaces = new \jsys\types\Text($testString);
    }
    public function test_must_initialize_with_some_space()
    {
        $testString = "  ";
        $spaces = new \jsys\types\Text($testString);
        $this->assertInstanceOf('jsys\types\Text', $spaces);
        $this->assertEquals('jsys\types\Text', get_class($spaces));
        $this->assertEquals($spaces->getStr(), $testString, 'Both must get the same value');
    }



    public function tearDown(): void
    {
    }
}