<?php
declare(strict_types=1);
namespace Jsys\strings\Test;

use jsys\types\strings\Text;
use PHPUnit\Framework\TestCase;


class HasSpaceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_given_string_must_have_one_space()
    {
        $testString = 'helloworld';
        $this->expectExceptionCode(1027);
        $this->expectExceptionMessage("Given '$testString' has atleast one space");
        $spaces = new Text($testString);
        $spaces->hasSpace();
    }
    public function test_must_initialize_with_some_space()
    {
        $testString = "hello world";
        $spaces = new Text($testString);
        $spaces->hasSpace();
        $this->assertInstanceOf('jsys\types\strings\Text', $spaces);
        $this->assertEquals('jsys\types\strings\Text', get_class($spaces));
        $this->assertEquals($spaces->value(), $testString, 'Both must get the same value');
    }



    public function tearDown(): void
    {
    }
}