<?php
declare(strict_types=1);
namespace Jsys\strings\Test;

use jsys\types\strings\Text;
use PHPUnit\Framework\TestCase;


class IsSpaceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_not_initialize_without_any_space()
    {
        $testString = '';
        $this->expectExceptionCode(1023);
        $this->expectExceptionMessage("Given '$testString' has no space");
        $spaces = new Text($testString);
        $spaces->isSpace($testString);
    }
    public function test_must_initialize_with_some_space()
    {
        $testString = " ";
        $spaces = new Text($testString);
        $spaces->isSpace($testString);
        $this->assertInstanceOf('jsys\types\strings\Text', $spaces);
        $this->assertEquals('jsys\types\strings\Text', get_class($spaces));
        $this->assertEquals($spaces->value(), $testString, 'Both must get the same value');
    }



    public function tearDown(): void
    {
    }
}