<?php
declare(strict_types=1);

namespace Jsys\Http\Test;

use NonWhiteSpaceString;
use PHPUnit\Framework\TestCase;


class NonWhiteSpaceStringTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_not_initialize_with_white_space_string()
        {
        $testString = ' ';
        $this->expectExceptionCode(1002);
        $this->expectExceptionMessage("Given string '$testString' contain non white space.");
        $nonWhiteString = new NonWhiteSpaceString($testString);
    }

    public function test_can_initialize_with_non_white_space_string()
    {
        $testString = '';
        $nonWhiteSpaceString = new NonWhiteSpaceString($testString);
        $this->assertInstanceOf('NonWhiteSpaceString', $nonWhiteSpaceString);
        $this->assertEquals('NonWhiteSpaceString', get_class($nonWhiteSpaceString));
        $this->assertEquals($nonWhiteSpaceString->value(), $testString, 'Both must get the same value');
    }

    public function tearDown(): void
    {
    }
}
