<?php
declare(strict_types=1);

namespace Jsys\strings\Test;
use jsys\types\strings\Text;
use PHPUnit\Framework\TestCase;


class StringLengthTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_return_length_of_given_string()
    {
        $testString = "hello";
        $nonEmptyString = new Text($testString);
        $nonEmptyString->length($testString);
        $this->assertInstanceOf('jsys\types\strings\Text', $nonEmptyString);
        $this->assertEquals('jsys\types\strings\Text', get_class($nonEmptyString));
        $this->assertEquals($nonEmptyString->value(), $testString, 'Both must get the same value');
    }



    public function tearDown(): void
    {
    }
}