<?php
declare(strict_types=1);

namespace Jsys\strings\Test;
use jsys\types\strings\Text;
use PHPUnit\Framework\TestCase;


class StringLengthTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_must_not_initialize_with_empty_string_length()
    {
        $testString = '';
        $this->expectExceptionCode(1801);
        $this->expectExceptionMessage(''.$testString.' should have some length');
        $nonWhiteString = new Text($testString);
        $nonWhiteString->length($testString);
    }
    public function test_must_initialize_with_some_string_length()
    {
        $testString = "hello";
        $nonEmptyString = new Text($testString);
        $this->assertInstanceOf('jsys\types\strings\Text', $nonEmptyString);
        $this->assertEquals('jsys\types\strings\Text', get_class($nonEmptyString));
        $this->assertEquals($nonEmptyString->value(), $testString, 'Both must get the same value');
    }



    public function tearDown(): void
    {
    }
}